### ISSUE TITLE
Lyrics JSON response

### ISSUE THREAD

**Issue by pR0Ps** [spl0k/supysonic#136]
The JSON response to lyrics currently looks like this:
```
{
    "subsonic-response": {
        "lyrics":{
            "_value_":"lyrics here",
            "artist":"the aritst",
            "title":"the title"
        },
        "status":"ok",
        "version":"1.9.0"
    }
}
```
The DSub and Ultrasonic Android apps expect lyrics to be in a key called `value`, not `_value_` so they currently don't display anything. See their testcase here: https://github.com/ultrasonic/ultrasonic/blob/1dc3b512c8f8b45c4ab2e5934c9c8ecfc0f0b68f/subsonic-api/src/integrationTest/resources/get_lyrics_ok.json . I verified this by changing the key name in Supysonic as a test.

Is this a problem on their end or in this project? I can't seem to find any real documentation on Subsonic API JSON responses anywhere (or general rules for XML -> JSON conversions) so I'm not sure which project should be fixed. Do you have any links to a reference or something?

**Comment by spl0k** [comment]
This `_value_` key *I* arbitrarily chose to handle the case when, for the XML format, some string needed to go as a text child element rather than an attribute. This behaviour can be seen when requesting [lyrics](http://www.subsonic.org/pages/inc/api/examples/lyrics_example_1.xml) or [genres](http://www.subsonic.org/pages/inc/api/examples/genres_example_1.xml).
Unfortunately this ability of XML for an element to have both attributes and a textual value can't be expressed in JSON and, as you noted, the Subsonic documentation doesn't give any information about how those cases should be formatted.

Testing on the [official Subsonic demo](http://demo.subsonic.org/rest/getLyrics.view?u=guest4&p=guest&c=web&v=1.8.0&artist=clash&title=london&f=json) it seems DSub and Ultrasonic are right about the `value` key, so the issue is on our end.
