### ISSUE TITLE
Add a new version tag with latest changes

### ISSUE THREAD

**Issue by ogarcia** [spl0k/supysonic#195]
@spl0k can you add a new version tag (0.5.1 maybe) with latest changes? Is to update [the docker](https://github.com/ogarcia/docker-supysonic) ;-)

**Comment by spl0k** [comment]
Done.

I was actually waiting for podcast support (#188) to land before pushing a new version, but I guess I should think of a better/more consistent release strategy.

On a side note, I understand the need to have well-known releases/version, but if you want to be cutting edge why don't you set your docker scripts to pull from master rather than a tag?
