### ISSUE TITLE
publish releases to PyPI

### ISSUE THREAD

**Issue by khimaros** [spl0k/supysonic#204]
this would ease installation considerably.

**Comment by spl0k** [comment]
I don't know why, I've always considered this as a repository for libraries aimed at developers, not something for software distribution.
Well I'll look into it then.

**Comment by pR0Ps** [comment]
@spl0k Even without publishing to PyPI, making this installable entirely from a package would allow people to run `pip install git+https://github.com/spl0k/supysonic` instead of having to clone it to a directory and install it. This would make it much easier to install as well as update.

Since you're already using Flask/Jinja2, a lot of the pain points of doing this (ie. loading templates and static files from the package) are mostly handled for you. If you want a simple example (<150 LOC + assets), [an older project of mine](https://github.com/pR0Ps/strava-tokengen) is packaged in this way. Specifically see [`setup.py`'s `package_data`](https://github.com/pR0Ps/strava-tokengen/blob/efa14f29e13a4b57bafb477d74084a88946b4f2b/setup.py#L19), [the `jinja2.Environment` object](https://github.com/pR0Ps/strava-tokengen/blob/efa14f29e13a4b57bafb477d74084a88946b4f2b/strava_tokengen/__init__.py#L35-L38), and [loading a packaged file](https://github.com/pR0Ps/strava-tokengen/blob/efa14f29e13a4b57bafb477d74084a88946b4f2b/strava_tokengen/__init__.py#L128).

**Comment by spl0k** [comment]
Well actually you could run `pip install git+https://github.com/spl0k/supysonic` to install it, but the's no entry point to run the webserver.
I'll keep your pointers around, they may not be necessary since `setup.py` declares `zip_safe=False`, but I've read some people advising against the use of this flag...

**Comment by spl0k** [comment]
Hey all!
There's a new Supysonic version available, and it's installable with `pip`.

I might have messed up a bit the release on PyPI (I noticed an installation issue _after_ I uploaded 😑) so you might get a warning from `pip` but it should still install and run properly.
