### ISSUE TITLE
Pip failure on Windows

### ISSUE THREAD

**Issue by JSonnabend** [spl0k/supysonic#231]
I am trying to install on Windows 10. I have Python 3.10 installed and have coded some other projects in it. PIP worked for those projects. I am getting an error with supysonic:

```
E:\>pip install supysonic
ERROR: Could not find a version that satisfies the requirement supysonic (from versions: none)
ERROR: No matching distribution found for supysonic
```

**Comment by spl0k** [comment]
Hello.
The version on PyPI isn't compatible with Python 3.10 yet. I'll try to publish a new version this weekend.
In the meantime you can install it from the git repository with the following command:

```
$ pip install git+https://github.com/spl0k/supysonic.git
```

As a side note, since you're on Windows you won't be able to use Gunicorn (if you're installing by just following the quickstart section from the readme), so you should install Waitress or Gevent instead.

**Comment by JSonnabend** [comment]
Thanks for the quick response. Installing now . . .

**Comment by spl0k** [comment]
Supysonic 0.7.2, with Python 3.10 support, is now available on PyPI 🚀
