### ISSUE TITLE
supysonic-server command not available

### ISSUE THREAD

**Issue by jimToo** [spl0k/supysonic#236]
Hi,
I tried to setup supysonic on a debian (stable) server:

after install:
$ apt install supysonic gunicorn3

I cannot start the webserver:
**"supysonic-server" command not found.**

$ whereis supysonic-server
is empty...
"supysonic-cli" is working.

supysonic debian package in stable is "0.6.2"

What am I doing wrong?

Thanks for some hints!

**Comment by spl0k** [comment]
Hello.
The `supysonic-server` command was added in version 0.7.0. You have several options to run Supysonic. If you want the to get the latest release (0.7.2) you can install `pip` with `apt` (the package is `python3-pip`) and then install Supysonic from `pip`:
```
# apt install python3-pip
# pip install supysonic
```
I don't know how `pip` behaves in that case but this might mess up your Python installation and mix libraries installed from Debian packages and from PyPI. So I wouldn't recommend installing Supysonic directly as described above without setting up a virtual environment beforehand.

Or, if you want to keep the Supysonic version provided by the debian repository, since you already installed Gunicorn you can run a Supysonic server by invoking Gunicorn:
```
$ gunicorn -b 0.0.0.0:5000 "supysonic.web:create_application()"
```
This will listen on all interfaces on port 5000. You've got a few more details in [the documentation](https://supysonic.readthedocs.io/en/0.6.3/setup/deploying/wsgi-standalone.html#gunicorn).

I have no control over which version is published in the Debian packages, and I don't really know how this whole process works. But if I'm not mistaken the 0.7.2 is available for bookworm (Debian testing).

Hope this helps.

**Comment by jimToo** [comment]
Thanks Alban, for fast response.

Starting standalone  `gunicorn "supysonic.web:create_application()"` it says:
"ModuleNotFoundError: No module named 'supysonic'"

I will try to use the debian package from "testing". This makes it a lot more easier.

Greetings Jim
