### ISSUE TITLE
supysonic-daemon settings

### ISSUE THREAD

**Issue by jimToo** [spl0k/supysonic#240]
Hello,

how can I start the "supysonic-daemon" with the option for supersonic-server to listen on localhost (not on 0.0.0.0)?

background: I am using nginx as reverse proxy

**Comment by spl0k** [comment]
Hello.
The daemon has no influence on which interface the web server listens on. The listening interface can only be set by the arguments used when starting `supysonic-server`. If you want it to listen on localhost, you can start it this way:
```
> supysonic-server --host 127.0.0.1
```
and it will listen on localhost, port 5722.

But since you're planning to use it behind a nginx reverse proxy on the same machine I would recommend using a Unix-domain socket instead. Then you can configure nginx to forward the requests to this socket rather than a inet address. On Supysonic's side it can be done by specifying the `--socket` argument:
```
> supysonic-server --socket /path/to/the/socket
```

All possible arguments can be found on [`supysonic-server` manpage](https://supysonic.readthedocs.io/en/latest/man/supysonic-server.html).

**Comment by jimToo** [comment]
I didn't get that the daemon is independent. (I thought the daemon is starting supysonic-server in background). Thanks for clarification!

I could also access supysonic with a unix-socket. Is this faster or why should I prefer over "localhost".

Greetz Jim

**Comment by spl0k** [comment]
Both options are viable but I tend to prefer Unix sockets for local communications. Since they don't rely on the TCP stack you could achieve better performance using Unix sockets rather than the loopback interface, but that performance difference will most likely only be relevant when under high traffic.

**Comment by jimToo** [comment]
thanks a lot! Supysonic is awesome :star:

**Comment by spl0k** [comment]
Glad you like it :)
