### ISSUE TITLE
Support creating playlists from m3u playlist files

### ISSUE THREAD

**Issue by davidbrenner** [spl0k/supysonic#34]
I'd like to be able to create playlists from .m3u files. I've written a very rough patch to do this on my own repo of supysonic here: c13b3aeaaa9bdf0a435a48cca85505f466f948fe. I just added a route to upload playlists to the frontend to implement it. The path for the uploads and the upload form are both hardcoded and ugly and the error handling is pretty awful, so it should probably be cleaned up before being pulled in. I can do that if there's interest in it.

One other issue related to error handling - due to the way the database is organized, multiple copies of the same song cannot be in the same playlist. I'm not sure how subsonic itself handles it, maybe that's consistent, but to me it's annoying. I'd like the option to have multiple of the same songs. I may end up changing this as well.

**Comment by davidbrenner** [comment]
Any interest in having this as a feature? Should I try to clean it up or just continue using it for myself?

**Comment by spl0k** [comment]
It'll be difficult to get something that works.
The M3U format allows both absolute and relative paths. Relative paths require that the playlist file to be created in a well known location, such as one of the root music folders. Playlists with absolute paths would only work if they are created on the computer running the server or if the the server have the same directory structure as the computer we're uploading the playlist from.
Those are strong conditions which are unlikely to be met in the general case.

**Comment by andrenam** [comment]
Indeed, the general scenario does not always work like that. 
Personally, I use supysonic and mpd both on the same server. I synchronize supysonic's playlist and mpd's playlist via a custom cronjob, but I realize that's not meant to be merged into the upstream version. :-)

**Comment by anarcat** [comment]
@andrenam how do you import playlists from a cronjob? i'd love to do that myself...

i looked at the database layout and couldn't make head or tails of it. for example, I just created a playlist from an album and supysonic created this in the MySQL database:

```
MariaDB [supysonic]> select id,tracks from playlist\G
*************************** 1. row ***************************
    id: ��PN�i@��Ƕ
                  �7
tracks: 7ccb5785-69e0-44e7-81d9-834c11d35028,561cc6be-0550-4a1e-be70-10591362819f,811c749a-9a7b-4a57-a69a-8f54e615337c,54a340d0-3d2b-46dd-832e-15e0555142ca,c1ad9e8e-c208-418c-a371-932f66ed81e7,0b9ccf41-ca25-486c-8de6-d657e0f6994b,11427740-2cff-4e20-a59a-babc9effd6f9,aa4db976-80c1-4129-bb08-fdd5beebddd9,fec80de3-5f6c-4213-b82c-256d4744023c,16cdf38d-2a48-41cc-bb9d-3383de4efa14,e18844bb-e7b8-4b33-956a-7293a6e61b0d,119386aa-fa5f-4da3-b661-50866d5e2dab
```

The first thing that surprised me are the `BINARY` fields like `id` here. But then I'm puzzled by the `tracks` column as well: those look like UUIDs but I can't find the same entries in the `track` table...

I was hoping I could just sync on-disk m3u playlists I generate from mpd into supysonic as well, so I would *really* like to see how @andrenam does their cronjob things. :)

**Comment by spl0k** [comment]
Primary keys are all UUIDs. Pony tends to store them as their binary representation, you'll have more luck making sense of them on PostgreSQL since it natively support this type. The `tracks` column here are the "human readable" UUIDs referencing entries on the `track` table. They're handled on the Python side. This is a comma-separated list string because I was too lazy at the time to define a proper many-to-many relation.

I don't know about @andrenam setup, but at that time Supysonic used storm rather than PonyORM, and storm stored UUIDs in a nicer representation than Pony does.

**Comment by anarcat** [comment]
oh wow, weird. binary UUIDs. :) i did not know this was a PostgreSQL thing... it might be worth outlining  pgsql as the primary supported database if weird stuff like that happens in MySQL :) But it seems MySQL 8 (?!) has added support for UUIDs according to [this post](https://mysqlserverteam.com/mysql-8-0-uuid-support/). And there seems to be a [BIN_TO_UUID](https://dev.mysql.com/doc/refman/8.0/en/miscellaneous-functions.html#function_bin-to-uuid) function I can use to do magic stuff with it, so it seems I might be able to get away with this without having to deploy a pgsql cluster.

In any case, I think it would be great to have something like what @davidbrenner proposed. His patch has some site-specific stuff embeded and would need a little cleaning up, but otherwise it seems sound to me.

Another thing to work on for me, I guess. :)

**Comment by andrenam** [comment]
@anarcat: I can get back to you maybe next weekend, as I'm in the middle of moving houses.
Back in the day, I didnt touch the database directly but used python, imported the relevant supysonic modules and used that to store/add playlists.

**Comment by anarcat** [comment]
On 2019-04-06 06:48:02, nambot wrote:
> @anarcat: I can get back to you maybe next weekend, as I'm in the middle of moving houses.
> Back in the day, I didnt touch the database directly but used python, imported the relevant supysonic modules and used that to store/add playlists. 

That's fine, take your time. :) This is already very useful
information, and any code sample you can throw at us will help
tremendously!

Thanks!

**Comment by anarcat** [comment]
hello @andrenam ! how was the move? :) did you have time to look into this again? any code you can share with out would be very helpful... thanks!
