### ISSUE TITLE
PolySonic won't connect to supysonic

### ISSUE THREAD

**Issue by tkiapril** [spl0k/supysonic#36]
[PolySonic] (https://chrome.google.com/webstore/detail/polysonic/dmijgonnbeadbncajpphnlidgjkgmblf?hl=en) is a decent, clean-looking client software for Subsonic API. It runs as a Google Chrome extension.
When I try to connect it to an instance of supysonic, it would return an error without proper explanation. On the server side, I only get a line of log (when debugging):

```
10.8.8.1 - - [13/Aug/2015 02:05:05] "GET /rest/ping.view?u=test&p=test&v=1.11.0&c=PolySonic&f=json HTTP/1.1" 200 -
```

and nothing afterwards.

Since other clients such as Jamstash, Perisonic, DSub and Subsonic on Android works, it would not be a major problem. However, I assume a slightest chance of some compatibility issue since PolySonic works with the official server software.

I could not determine if it is a problem on the server side or client side. Some differences between supysonic and Subsonic that I was able to find out was:
* Different indentation of JSON: one space versus three spaces
* Subsonic uses the Content-Type: `application/json; charset=utf-8` while supysonic was missing the charset part.
* Subsonic uses gzipped response for default and sends its response with chunked transfer.
* Different API versions: 1.8.0 v 1.12.0. (Although I feel skeptical about the effect of this difference)

You may refer to the code at: [https://github.com/dough10/PolySonic] (https://github.com/dough10/PolySonic).

**Comment by tkiapril** [comment]
Maybe this can be a hint: when using jsonp mode on Jamstash, it worked normally, but when I try to use the json mode, simillar issue arises: nothing comes after the first ping.

**Comment by spl0k** [comment]
I fixed the issue with Jamstash and JSON (541efa6437c1f43eeea146f0acb44b0e04bda50e)
As for Polysonic, it now get past the login screen but then just display its logo along with an infinite spinner. This is because Polysonic use the new authentication method introduced with the version 1.13.0 of the Subsonic API (except at login where it sends the password in plain text), and Supysonic doesn't support the method.

I don't think I'll implement this new authentication method in Supysonic though. Sure it improves the security on the client side (password no longer transmitted as plain text or as an easily reversed cypher) but it requires the server to store the password as plain text in the database, which I don't want to.

**Comment by tkiapril** [comment]
Ah, I got it. That's kinda strange... That seems to mean that vanilla subsonic has been using plain text for passwords on database until now.

**Comment by spl0k** [comment]
And still does.

**Comment by spl0k** [comment]
PolySonic fixed its version detection code to fallback on the old authentication method when the server is running on an old version of the API. So supysonic now works with PolySonic.
