### ISSUE TITLE
Capitalization-unaware search

### ISSUE THREAD

**Issue by tkiapril** [spl0k/supysonic#41]
Currently, the search method finds only for strings that matches exactly, which means that the user has to type the query with exact capitalization.
It would be great if this could be worked out.

**Comment by andrenam** [comment]
Form your previous comments, I gathered you're using PostgreSQL. PostgreSQL's LIKE is dass sensitive - in constrast to SQLite or  Mysql/mariadb. 

One would have to get storm to use ILIKE instead of LIKE. I don't know why spl0k switched to storm. It's poorly documented and the project is dead anyways. I can't find much information about ``storm.expr.Column.contains_string``string``, so you probably have to dig into storm's source. Have fun.

**Comment by tkiapril** [comment]
Well, that sure sounds like a bit of headache.
From what I have searched a bit, I found this link: https://bugs.launchpad.net/storm/+bug/134348
Does it sound like if the so-called ILIKE issue has been worked out on Storm side?
