### ISSUE TITLE
Drop "daemon-runner" wrapper in favor of strait "python-daemon" for the watcher

### ISSUE THREAD

**Issue by baldurmen** [spl0k/supysonic#72]
Hi!

While trying to run the watcher, I got his dependency error:

    ImportError: No module named daemon.runner

This is of course the result of me not installing supysonic via pip but with Debian packages.

Sadly, is does not seem like [daemon-runner](https://pypi.python.org/pypi/daemon-runner) is packaged for Debian. [python-daemon](https://pypi.python.org/pypi/python-daemon/), the library under the daemon-runner wrapper is though.

I was thus wondering how hard it would be to drop the wrapper and use the base library instead.

I'm not closed to the idea of doing the PR myself, I've just never touched that python lib before and was wondering if you could explain you design choice.

**Comment by spl0k** [comment]
I don't remember why I choose one lib over the other, most likely it was because I was following some tutorial and took the first thing that best fit my needs. It was the first time I worked with daemons.

The best course of action would be, I think, to drop the whole daemon thing altogether and just make a non-forking foreground process. That would make the watcher more systemd-friendly (see #37)
