### ISSUE TITLE
Jukebox mode?

### ISSUE THREAD

**Issue by sprnza** [spl0k/supysonic#88]
Hi there!
Just curious. Why jukebox mode is not goin to be implemented? Is there some technical limitations or it's just strategic decision?

**Comment by spl0k** [comment]
Hi.
First of all because I'd like to stick to the _server_ concept. Its sole purpose should be _serving_ data to clients requesting it, not acting like some audio player.
Furthermore I don't want to add dependencies on audio processing libraries or other specific software.

**Comment by sprnza** [comment]
@spl0k, thanks for the reply.

**Comment by anarcat** [comment]
plenty of audio servers actually do implement audio playback. `mpd` for example, is one of those. subsonic is another one. :)

i would encourage you to reconsider; I'm considering switching away from MPD and two things are missing in the Subsonic ecosystem for me:

 1. a proper desktop client - nothing you can do about here of course
 2. a lightweight server - supysonic looks like a nice alternative, but is lacking jukebox support

How would one implement a jukebox with supysonic? Is there a dumb, headless Subsonic player that would obey Jukebox commands? This would be weird because the API requests would need to be channeled through a different endpoint... 

Playing audio is not that complicated... In the past, I've had good luck with pygame to play simple sounds, but music players like [Quodlibet](https://github.com/quodlibet/quodlibet/) talk with gstreamer through the `gi` interface. [MusicPlayer](http://albertz.github.com/music-player/) is another that has its [own library](https://pypi.python.org/pypi/musicplayer) that could be interesting...

**Comment by spl0k** [comment]
It's been some time, but the 0.5.0 version finally brings the jukebox mode.

Rather than adding some audio playback library I went on using an user-defined external player (such as `mplayer`). Because of this there might be a small error in playback progress and you won't be able (yet?) to set the output volume.
Users will need a new role to be able to use the jukebox.
This jukebox mode requires the daemon to be running.
Some details can be found on the [documentation](https://github.com/spl0k/supysonic/blob/master/docs/jukebox.md).

It might need some more work but it seems to be working well enough.

:christmas_tree: Merry Christmas :gift:

**Comment by clach04** [comment]
Worth closing this ticket down now that this feature is available?

**Comment by spl0k** [comment]
Hello. I tend to leave issues open when I consider more work could be put into it, but I don't remember what I had in mind with this one. So I'll close it ;)
